version: '3.8'

services:
  backend:
    volumes:
      - ./backend/app:/app:rw
    environment:
      - DEV=true

  frontend:
    volumes:
      - ./frontend:/app:rw
      - frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DEV=true

volumes:
  frontend_node_modules:
    driver: local
